# _config.yml
title: Routine Checkup
email: info@routinecheckup.com
description: >-
  Cloud Checks
baseurl: ''
url: 'https://routinecheckup.com'
repository:  'routinecheckup-com/routinecheckup-com.github.io'

# Build settings
remote_theme: 'mmistakes/minimal-mistakes@4.22.0'

plugins:
  - jekyll-feed
  - jekyll-remote-theme

include: ['_pages']

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
